/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Database": {
      "accountId": string
      "databaseId": string
      "token": string
      "type": "sst.cloudflare.D1"
    }
    "Search": import("@cloudflare/workers-types").Service
    "Urls": {
      "api": string
      "site": string
      "type": "sst.sst.Linkable"
    }
    "Web": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}