/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DownloadsHandler": import("@cloudflare/workers-types").Service
    "Ingest": import("@cloudflare/workers-types").Queue
    "Search": import("@cloudflare/workers-types").Service
    "Snapshots": import("@cloudflare/workers-types").R2Bucket
    "SyncHandler": import("@cloudflare/workers-types").Service
  }
}

import "sst"
export {}