/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DailyRefreshHandler": import("@cloudflare/workers-types").Service
    "Database": import("@cloudflare/workers-types").Hyperdrive
    "GcpConfig": {
      "project": string
      "type": "sst.sst.Linkable"
    }
    "GcpServiceAccountKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonDatabase": {
      "connectionString": string
      "host": string
      "name": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "user": string
    }
    "Search": import("@cloudflare/workers-types").Service
    "Urls": {
      "api": string
      "site": string
      "type": "sst.sst.Linkable"
    }
    "Web": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}