import { expect, test } from "bun:test";
import { parseKeywords } from "./parse-keywords";

test("parseKeywords", () => {
  const pairs: Array<[string, string[]]> = [
    [
      "creatorsarea, jobs, api, client, sdk, garry's-mod, gmod, freelance",
      ["creatorsarea", "jobs", "api", "client", "sdk", "garry's-mod", "gmod", "freelance"],
    ],
    [
      "immutable hashable picklable frozendict dict dictionary map Mapping MappingProxyType developers stable utility",
      [
        "immutable",
        "hashable",
        "picklable",
        "frozendict",
        "dict",
        "dictionary",
        "map",
        "Mapping",
        "MappingProxyType",
        "developers",
        "stable",
        "utility",
      ],
    ],
    [
      "convert, docutils, pdf, pygments, reportlab', restructured, rst",
      ["convert", "docutils", "pdf", "pygments", "reportlab", "restructured", "rst"],
    ],
    ["tarnfeld,tarnfeid,tarn,can't handle my", ["tarnfeld", "tarnfeid", "tarn", "can't handle my"]],
    ["'cloud restful service'", ["cloud", "restful", "service"]],
    [
      "git commit add push files context manager doesnt-git-easier doesn't get easier",
      [
        "git",
        "commit",
        "add",
        "push",
        "files",
        "context",
        "manager",
        "doesnt-git-easier",
        "doesn't",
        "get",
        "easier",
      ],
    ],
    [
      '"cobertura coverage diff report parser parse xml"',
      ["cobertura", "coverage", "diff", "report", "parser", "parse", "xml"],
    ],
    ['"oss, aio"', ["oss", "aio"]],
    [
      "fastapi,cloudevents[pydantic],ce,cloud,events,event,middleware,rest,rest-api,plugin,pydantic,fastapi-extension",
      [
        "fastapi",
        "cloudevents[pydantic]",
        "ce",
        "cloud",
        "events",
        "event",
        "middleware",
        "rest",
        "rest-api",
        "plugin",
        "pydantic",
        "fastapi-extension",
      ],
    ],
    [
      '"AI toolkit", "password generator", "secure passwords", "password strength checker", "password encryption", "password decryption", "token generator", "API key generator", "data masking", "PII protection", "sensitive data protection", "privacy tools", "RAG", "LLM", "AI security", "Python security library", "secure password management", "custom password generation", "random number generation"',
      [
        "AI toolkit",
        "password generator",
        "secure passwords",
        "password strength checker",
        "password encryption",
        "password decryption",
        "token generator",
        "API key generator",
        "data masking",
        "PII protection",
        "sensitive data protection",
        "privacy tools",
        "RAG",
        "LLM",
        "AI security",
        "Python security library",
        "secure password management",
        "custom password generation",
        "random number generation",
      ],
    ],
    ['genetic programming","symbolic learning', ["genetic programming", "symbolic learning"]],
    [
      'isnumeric,is_numeric,number,isnumber,is_number,"is numeric","is number",numeric',
      [
        "isnumeric",
        "is_numeric",
        "number",
        "isnumber",
        "is_number",
        "is numeric",
        "is number",
        "numeric",
      ],
    ],
    ['WPS INCF "Digital Atlasing"', ["WPS", "INCF", "Digital Atlasing"]],
    [
      "agent, fastmcp, llm, mcp, mcp client, mcp server, model context protocol",
      ["agent", "fastmcp", "llm", "mcp", "mcp client", "mcp server", "model context protocol"],
    ],
    [
      "['VRP','Branch-Cut-&Price','Operations Research','Optimization','Linear Programming','Routing problems','Solver','Supply chain']",
      [
        "VRP",
        "Branch-Cut-&Price",
        "Operations Research",
        "Optimization",
        "Linear Programming",
        "Routing problems",
        "Solver",
        "Supply chain",
      ],
    ],
    [
      "[django, template, block, templates, render, context]",
      ["django", "template", "block", "templates", "render", "context"],
    ],
    [
      '{"ecg analysis","pytorch","pretrained models","ecg preprocessing","ecg datasets"}',
      ["ecg analysis", "pytorch", "pretrained models", "ecg preprocessing", "ecg datasets"],
    ],
    [
      "{physics,pre-university,bachiller,uarm,kinematics,dynamics,energy conservation,gravitational field,electrical field}",
      [
        "physics",
        "pre-university",
        "bachiller",
        "uarm",
        "kinematics",
        "dynamics",
        "energy conservation",
        "gravitational field",
        "electrical field",
      ],
    ],
    ["Python, ", ["Python"]],
    [", , ", []],
    ["(bottle,pycassa,cassandra)", ["bottle", "pycassa", "cassandra"]],
    ['"machine, learning, nlp', ["machine", "learning", "nlp"]],
    ['", b', ["b"]],
    ['a, "b, c', ["a", "b", "c"]],
  ];

  for (const [input, expected] of pairs) {
    expect(parseKeywords(input)).toEqual(expected);
  }
});
